class NotAllowedError(Exception):
    pass


class AlreadyExistsError(Exception):
    pass
